run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: "demo"
        subdir: demo
    log: 
        debug_en: False
gpt: 
    model: /home/nvidia/data/models/Qwen3-8B
    rtlgen_model: /home/nvidia/data/models/Qwen3-8B
autoline: 
    probset: 
        path: data/HDLBits/HDLBits_data.jsonl
        mutant_path: data/HDLBits/HDLBits_data_mutants.jsonl
        more_info_paths: ['data/HDLBits/HDLBits_data_RTL_4o_20.jsonl']
        only: ["mux2to1v"]
    promptscript: pychecker
    timeout: 40
    save_compile: True
    debug: 
        max: 3
    itermax: 10
    update_desc: False
    TBcheck: 
        discrim_mode: col_70_wrong_row_25_correct